# Numpy

In [1]:
import numpy as np

In [2]:
a1=np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[1, 2.0, 3.3], [4, 5, 6]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

#### Properties & Attributes 
1. shape
2. ndim
3. size
4. itemsize `error`
5. dtype
6. astpye()

In [4]:
a1.shape

(3,)

In [5]:
a2.shape

(2, 3)

In [6]:
a1.ndim

1

In [7]:
a1.size

3

In [8]:
a1.dtype

dtype('int32')

In [11]:
a1.astype('int')

array([1, 2, 3])

#### Lists Vs Arrays 
1. Faster 
2. Convenient 
3. Less Memory 

# Numpy Array Operations  

## 1. Basic Operations  
- **a.** \( A - b \)  
- **b.** \( b^2 \)  
- **c.** \( A^{c} \)  
- **d.** \( A \cdot B \) (Element-wise multiplication)  
- **e.** \( A.dot(B) \)  
- **f.** \( A = B \)  

## 2. Unary Operations  
- **a.** A.min() and A.max()  
- **b.** A.sum(axis=0) 

## 3. Universal Functions  
- **a.** np.exp(A)  
- **b.** np.sqrt(A)
- **c** np.sin(A)

In [2]:
import numpy as np
ar1=np.array([1, 2, 3])
ar2=np.array([4, 5, 6])


In [3]:
ar1 + ar2

array([5, 7, 9])

In [4]:
ar1-ar2

array([-3, -3, -3])

In [5]:
ar1*ar2

array([ 4, 10, 18])

In [6]:
ar1/ar2

array([0.25, 0.4 , 0.5 ])

In [7]:
ar1>2

array([False, False,  True])